version: "3.7"

services:
  frontend-service:
    container_name: frontend
    hostname: frontend
    build: './'
    ports:
      - "4401:80"
    volumes:
      - ./:/usr/src/app
    command: ["npm", "run", "start"]
    networks:
      - cluster

networks:
  cluster:
    external: true
